# Generated by Django 5.2.7 on 2025-10-28 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('posicion', models.IntegerField()),
                ('localizador', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(default='00001', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Nombre Cliente', max_length=200)),
                ('razon_social', models.CharField(default='Razón Social Cliente', max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_agua', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_promedio_kg', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('codigoMat', models.CharField(blank=True, max_length=20, null=True)),
                ('nombreProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('unidadMedida', models.CharField(blank=True, max_length=50, null=True)),
                ('unidadCompra', models.CharField(blank=True, max_length=50, null=True)),
                ('unidadMinCompra', models.IntegerField(blank=True, null=True)),
                ('leadTimeDias', models.IntegerField(blank=True, null=True)),
                ('medioTransporte', models.CharField(blank=True, max_length=50, null=True)),
                ('reabastecimiento', models.IntegerField(blank=True, null=True)),
                ('terminoPago', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempoCreditoDias', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sellsOneWeek', models.FloatField(max_length=11)),
                ('sellsTwoWeek', models.FloatField(max_length=11)),
                ('sellsThreeWeek', models.FloatField(max_length=11)),
                ('sellsFourWeek', models.FloatField(max_length=11)),
                ('nequi', models.CharField(max_length=255)),
                ('daviplata', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idCajero', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCajero', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('salario', models.FloatField(default=0)),
                ('totalEarning', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=250)),
                ('nombreGenerico', models.CharField(blank=True, max_length=250, null=True)),
                ('stockProducto', models.IntegerField(default=0)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantAdquirida', models.IntegerField(default=0)),
                ('proveedor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor3', to='app.proveedor')),
                ('proveedor4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor4', to='app.proveedor')),
                ('proveedorPrincipal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to='app.proveedor')),
                ('proveedorSuplente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplente', to='app.proveedor')),
            ],
        ),
    ]
