# Generated by Django 3.2.24 on 2024-02-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('idCajero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCajero', models.CharField(max_length=100)),
                ('salario', models.FloatField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('numeroCompras', models.IntegerField(max_length=3)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.FloatField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nitProvider', models.IntegerField(primary_key=True, serialize=False)),
                ('nomProvider', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('precioCompra', models.FloatField(null=True)),
                ('ivaProducto', models.FloatField(null=True)),
                ('stockProducto', models.IntegerField(null=True)),
                ('nitProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('totalBruto', models.FloatField()),
                ('totalIva', models.FloatField()),
                ('subTotal', models.FloatField()),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('cedulaCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idCajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cajero')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('utilidad', models.FloatField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
    ]
