# Generated by Django 5.2.7 on 2025-10-14 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('idCajero', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCajero', models.CharField(max_length=100)),
                ('salario', models.FloatField(max_length=11)),
                ('correo', models.EmailField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=255)),
                ('totalEarning', models.FloatField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('numeroCompras', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.FloatField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('nombreGenerico', models.CharField(blank=True, max_length=200, null=True)),
                ('stockProducto', models.IntegerField(default=0)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantAdquirida', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('codigoMat', models.CharField(blank=True, max_length=20, null=True)),
                ('nombreProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('unidadMedida', models.CharField(blank=True, max_length=50, null=True)),
                ('unidadCompra', models.CharField(blank=True, max_length=50, null=True)),
                ('unidadMinCompra', models.IntegerField(blank=True, null=True)),
                ('leadTimeDias', models.IntegerField(blank=True, null=True)),
                ('medioTransporte', models.CharField(blank=True, max_length=50, null=True)),
                ('reabastecimiento', models.IntegerField(blank=True, null=True)),
                ('terminoPago', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempoCreditoDias', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('totalBruto', models.FloatField()),
                ('totalIva', models.FloatField()),
                ('subTotal', models.FloatField()),
                ('link', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('cedulaCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idCajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cajero')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('utilidad', models.FloatField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor3', to='app.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor4', to='app.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedorPrincipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to='app.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedorSuplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplente', to='app.proveedor'),
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sellsOneWeek', models.FloatField(max_length=11)),
                ('sellsTwoWeek', models.FloatField(max_length=11)),
                ('sellsThreeWeek', models.FloatField(max_length=11)),
                ('sellsFourWeek', models.FloatField(max_length=11)),
                ('nequi', models.CharField(max_length=255)),
                ('daviplata', models.CharField(max_length=255)),
                ('bestCashierMonth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cajero')),
            ],
        ),
    ]
