# Generated by Django 5.2.7 on 2025-10-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='stats',
            name='bestCashierMonth',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='idCajero',
        ),
        migrations.DeleteModel(
            name='Cajero',
        ),
    ]
