# Generated by Django 3.2.24 on 2024-02-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cajero',
            name='correo',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='cajero',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
