# Generated by Django 5.2.7 on 2025-10-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_storageitem_remove_stats_bestcashiermonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('posicion', models.IntegerField()),
                ('localizador', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
    ]
