# Generated by Django 3.2.24 on 2024-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240226_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidadMedidad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
