# Generated by Django 5.2.7 on 2025-10-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='idFactura',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombreCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numeroCompras',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cantidad_promedio_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='00001', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Nombre Cliente', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default='Razón Social Cliente', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_agua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
