# Generated by Django 5.2.7 on 2025-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_compra_idfactura_remove_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idCajero', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCajero', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('salario', models.FloatField(default=0)),
                ('totalEarning', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
