# Generated by Django 5.0.4 on 2024-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cajero_totalearning_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='daviplata',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='nequi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
