# Generated by Django 5.0.4 on 2024-04-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_stats_daviplata_stats_nequi'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
