# Generated by Django 5.2.5 on 2025-09-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_admin_id_alter_cajero_idcajero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cityProvider',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dirProvider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='emailProvider',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='phoneProvider',
            field=models.CharField(default='', max_length=11),
        ),
    ]
